policies:
  - name: default
    # defaultStrategy 优先级高于allowed
    defaultStrategy: "pap"
    allowed: 
      - "pap"
    sessionTimeout: 3600
    idleTimeout: 300
    redirectURL: "https://www.bing.com"